# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e6f6113c897a59fafee61df6f84478346109df0d9a54ccfc4da86bc085b1a72a21365127ac6d37db32a14c2f8736df0ebd770e2ca39d051743389b4b1d4d203

test:
  secret_key_base: d36cbf4e40a26dadf2a7acef9b77e3d9cd81030296cbdd608ffa0ca42e816ffc97f1c3cd02a9a011106d5cefc561e36024f1be04448d519809c6ae05d748bbee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
